

vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/altera_xcvr_functions.sv"                                               -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/alt_xcvr_resync.sv"                                                     -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/altera_xcvr_reset_control.sv"                                           -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/alt_xcvr_reset_counter.sv"                                              -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/sim/tb_tx_phyrst_ctl.v"                                                                                                                                        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/fifo_56_28/fifo_56_28/fifo_161/sim/fifo_56_28_fifo_161_jjnbjqy.v"                                                          -work fifo_56_28_fifo_161                            
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/fifo_56_28/fifo_56_28/sim/fifo_56_28.v"                                                                                                                                         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_a10_functions_h.sv"                                          -work altera_common_sv_packages                      
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_resync.sv"                                -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_arbiter.sv"                               -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pcs.sv"                                   -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pma.sv"                                   -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_avmm.sv"                             -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_native.sv"                           -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/a10_avmm_h.sv"                                     -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_pipe_retry.sv"                     -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_avmm_csr.sv"                       -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_prbs_accum.sv"                     -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_odi_accel.sv"                      -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_arb.sv"                       -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_params_h.sv"           -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_commands_h.sv"                           -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_functions_h.sv"                          -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_program.sv"                              -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_cpu.sv"                                  -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_master.sv"                               -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_ip.sv"                 -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/tx_jesd204b_altera_xcvr_native_a10_161_6d2kjaq.sv" -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_opt_logic_6d2kjaq.sv"         -l altera_common_sv_packages -work tx_jesd204b_altera_xcvr_native_a10_161         
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_phy_adapter_xs_161/sim/aldec/altera_jesd204_phy_adapter_xs.v"                                   -work tx_jesd204b_altera_jesd204_phy_adapter_xs_161  
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_mlpcs_161/sim/aldec/altera_jesd204_tx_mlpcs.v"                                               -work tx_jesd204b_altera_jesd204_tx_mlpcs_161        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_mlpcs_161/sim/aldec/altera_jesd204_8b10b_enc.v"                                              -work tx_jesd204b_altera_jesd204_tx_mlpcs_161        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_mlpcs_161/sim/aldec/altera_jesd204_tx_pcs.v"                                                 -work tx_jesd204b_altera_jesd204_tx_mlpcs_161        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_mlpcs_161/sim/aldec/altera_jesd204_wys_lut.v"                                                -work tx_jesd204b_altera_jesd204_tx_mlpcs_161        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_mlpcs_161/sim/aldec/altera_jesd204_xn_8b10b_enc.v"                                           -work tx_jesd204b_altera_jesd204_tx_mlpcs_161        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_mlpcs_161/sim/aldec/altera_jesd204_pcfifo.v"                                                 -work tx_jesd204b_altera_jesd204_tx_mlpcs_161        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_mlpcs_161/sim/aldec/altera_jesd204_mixed_width_dcfifo.v"                                     -work tx_jesd204b_altera_jesd204_tx_mlpcs_161        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_phy_161/sim/tx_jesd204b_altera_jesd204_phy_161_bhvxniy.v"                                       -work tx_jesd204b_altera_jesd204_phy_161             
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_161/sim/aldec/altera_jesd204_tx_base.v"                                                      -work tx_jesd204b_altera_jesd204_tx_161              
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_161/sim/aldec/altera_jesd204_tx_csr.v"                                                       -work tx_jesd204b_altera_jesd204_tx_161              
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_161/sim/aldec/altera_jesd204_tx_ctl.v"                                                       -work tx_jesd204b_altera_jesd204_tx_161              
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_161/sim/aldec/altera_jesd204_tx_dll.v"                                                       -work tx_jesd204b_altera_jesd204_tx_161              
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_161/sim/aldec/altera_jesd204_tx_regmap.v"                                                    -work tx_jesd204b_altera_jesd204_tx_161              
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_161/sim/aldec/altera_jesd204_tx_regmap_opt.v"                                                -work tx_jesd204b_altera_jesd204_tx_161              
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_tx_161/sim/aldec/altera_jesd204_tx_scrambler.v"                                                 -work tx_jesd204b_altera_jesd204_tx_161              
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_161/sim/tx_jesd204b_altera_jesd204_161_py6ow4q.v"                                               -work tx_jesd204b_altera_jesd204_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/sim/tx_jesd204b.v"                                                                                                                                                  
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/rom_port/rom_1port_161/sim/rom_port_rom_1port_161_m5cej6i.v"                                                               -work rom_port_rom_1port_161                         
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/rom_port/sim/rom_port.v"                                                                                                                                                        
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/altera_xcvr_functions.sv"                                              -work phyrst_controller_altera_xcvr_reset_control_161
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/alt_xcvr_resync.sv"                                                    -work phyrst_controller_altera_xcvr_reset_control_161
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/altera_xcvr_reset_control.sv"                                          -work phyrst_controller_altera_xcvr_reset_control_161
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/alt_xcvr_reset_counter.sv"                                             -work phyrst_controller_altera_xcvr_reset_control_161
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/sim/phyrst_controller.v"                                                                                                                                      
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_resync.sv"                                   -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_arbiter.sv"                                  -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pcs.sv"                                      -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pma.sv"                                      -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_avmm.sv"                                -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_native.sv"                              -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/a10_avmm_h.sv"                                        -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_pipe_retry.sv"                        -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_avmm_csr.sv"                          -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_prbs_accum.sv"                        -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_odi_accel.sv"                         -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_arb.sv"                          -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_params_h.sv"              -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_commands_h.sv"                              -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_functions_h.sv"                             -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_program.sv"                                 -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_cpu.sv"                                     -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_master.sv"                                  -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_ip.sv"                    -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/jesd204b_altera_xcvr_native_a10_161_ou2lroi.sv"       -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_opt_logic_ou2lroi.sv"            -l altera_common_sv_packages -work jesd204b_altera_xcvr_native_a10_161            
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_phy_adapter_xs_161/sim/aldec/altera_jesd204_phy_adapter_xs.v"                                      -work jesd204b_altera_jesd204_phy_adapter_xs_161     
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_rx_mlpcs.v"                                                  -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_8b10b_dec.v"                                                 -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_rx_pcs.v"                                                    -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_wa.v"                                                        -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_wys_lut.v"                                                   -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_xn_8b10b_dec.v"                                              -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_pcfifo.v"                                                    -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_mlpcs_161/sim/aldec/altera_jesd204_mixed_width_dcfifo.v"                                        -work jesd204b_altera_jesd204_rx_mlpcs_161           
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_phy_161/sim/jesd204b_altera_jesd204_phy_161_yorkvea.v"                                             -work jesd204b_altera_jesd204_phy_161                
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_base.v"                                                         -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_csr.v"                                                          -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_ctl.v"                                                          -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_descrambler.v"                                                  -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll.v"                                                          -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_char_val.v"                                                 -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_cs.v"                                                       -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_fs_char_replace.v"                                          -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_frame_align.v"                                              -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_lane_align.v"                                               -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_data_store.v"                                               -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_ecc_enc.v"                                                  -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_ecc_dec.v"                                                  -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_ecc_fifo.v"                                                 -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_dll_wo_ecc_fifo.v"                                              -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_rx_161/sim/aldec/altera_jesd204_rx_regmap.v"                                                       -work jesd204b_altera_jesd204_rx_161                 
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_161/sim/jesd204b_altera_jesd204_161_zta4dmq.v"                                                     -work jesd204b_altera_jesd204_161                    
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/sim/jesd204b.v"                                                                                                                                                        
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/core_pll/altera_iopll_161/sim/core_pll_altera_iopll_161_ep46qai.vo"                                                        -work core_pll_altera_iopll_161                      
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/core_pll/sim/core_pll.v"                                                                                                                                                        
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/twentynm_xcvr_avmm.sv"                                -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_resync.sv"                                   -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_arbiter.sv"                                  -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/a10_avmm_h.sv"                                        -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_atx_pll_rcfg_arb.sv"                         -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/a10_xcvr_atx_pll.sv"                                  -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_pll_embedded_debug.sv"                       -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_pll_avmm_csr.sv"                             -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/atx_pll_altera_xcvr_atx_pll_a10_161_25ew5mi.sv"       -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog       "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_atx_pll_rcfg_opt_logic_25ew5mi.sv"           -l altera_common_sv_packages -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlog -v2k5 "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/sim/atx_pll.v"                                                                                                                                                          
