// jesd204b_altera_jesd204_161_zta4dmq.v

// This file was auto-generated from altera_jesd204_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module jesd204b_altera_jesd204_161_zta4dmq #(
		parameter DEVICE_FAMILY            = "Arria 10",
		parameter SUBCLASSV                = 1,
		parameter PCS_CONFIG               = "JESD_PCS_CFG1",
		parameter L                        = 2,
		parameter M                        = 2,
		parameter F                        = 2,
		parameter N                        = 14,
		parameter N_PRIME                  = 16,
		parameter S                        = 1,
		parameter K                        = 16,
		parameter SCR                      = 1,
		parameter CS                       = 0,
		parameter CF                       = 0,
		parameter HD                       = 0,
		parameter ECC_EN                   = 0,
		parameter DLB_TEST                 = 0,
		parameter PHADJ                    = 0,
		parameter ADJCNT                   = 0,
		parameter ADJDIR                   = 0,
		parameter OPTIMIZE                 = 0,
		parameter DID                      = 0,
		parameter BID                      = 0,
		parameter LID0                     = 0,
		parameter FCHK0                    = 0,
		parameter LID1                     = 1,
		parameter FCHK1                    = 0,
		parameter LID2                     = 2,
		parameter FCHK2                    = 0,
		parameter LID3                     = 3,
		parameter FCHK3                    = 0,
		parameter LID4                     = 4,
		parameter FCHK4                    = 0,
		parameter LID5                     = 5,
		parameter FCHK5                    = 0,
		parameter LID6                     = 6,
		parameter FCHK6                    = 0,
		parameter LID7                     = 7,
		parameter FCHK7                    = 0,
		parameter JESDV                    = 1,
		parameter PMA_WIDTH                = 32,
		parameter SER_SIZE                 = 4,
		parameter FK                       = 32,
		parameter RES1                     = 0,
		parameter RES2                     = 0,
		parameter BIT_REVERSAL             = 0,
		parameter BYTE_REVERSAL            = 0,
		parameter ALIGNMENT_PATTERN        = 658812,
		parameter PULSE_WIDTH              = 2,
		parameter LS_FIFO_DEPTH            = 32,
		parameter LS_FIFO_WIDTHU           = 5,
		parameter UNUSED_TX_PARALLEL_WIDTH = 92,
		parameter UNUSED_RX_PARALLEL_WIDTH = 72,
		parameter XCVR_PLL_LOCKED_WIDTH    = 2,
		parameter RECONFIG_ADDRESS_WIDTH   = 11
	) (
		input  wire        pll_ref_clk,                //               pll_ref_clk.clk
		input  wire        rxlink_clk,                 //                rxlink_clk.clk
		input  wire        rxlink_rst_n_reset_n,       //              rxlink_rst_n.reset_n
		input  wire        jesd204_rx_avs_clk,         //        jesd204_rx_avs_clk.clk
		input  wire        jesd204_rx_avs_rst_n,       //      jesd204_rx_avs_rst_n.reset_n
		input  wire        jesd204_rx_avs_chipselect,  //            jesd204_rx_avs.chipselect
		input  wire [7:0]  jesd204_rx_avs_address,     //                          .address
		input  wire        jesd204_rx_avs_read,        //                          .read
		output wire [31:0] jesd204_rx_avs_readdata,    //                          .readdata
		output wire        jesd204_rx_avs_waitrequest, //                          .waitrequest
		input  wire        jesd204_rx_avs_write,       //                          .write
		input  wire [31:0] jesd204_rx_avs_writedata,   //                          .writedata
		output wire [63:0] jesd204_rx_link_data,       //           jesd204_rx_link.data
		output wire        jesd204_rx_link_valid,      //                          .valid
		input  wire        jesd204_rx_link_ready,      //                          .ready
		input  wire [63:0] jesd204_rx_dlb_data,        //       jesd204_rx_dlb_data.export
		input  wire [1:0]  jesd204_rx_dlb_data_valid,  // jesd204_rx_dlb_data_valid.export
		input  wire [7:0]  jesd204_rx_dlb_kchar_data,  // jesd204_rx_dlb_kchar_data.export
		input  wire [7:0]  jesd204_rx_dlb_errdetect,   //  jesd204_rx_dlb_errdetect.export
		input  wire [7:0]  jesd204_rx_dlb_disperr,     //    jesd204_rx_dlb_disperr.export
		input  wire        alldev_lane_aligned,        //       alldev_lane_aligned.export
		input  wire        sysref,                     //                    sysref.export
		input  wire        jesd204_rx_frame_error,     //    jesd204_rx_frame_error.export
		output wire        jesd204_rx_int,             //            jesd204_rx_int.irq
		output wire [3:0]  csr_rx_testmode,            //           csr_rx_testmode.export
		output wire        dev_lane_aligned,           //          dev_lane_aligned.export
		output wire        dev_sync_n,                 //                dev_sync_n.export
		output wire [3:0]  sof,                        //                       sof.export
		output wire [3:0]  somf,                       //                      somf.export
		output wire [7:0]  csr_f,                      //                     csr_f.export
		output wire [4:0]  csr_k,                      //                     csr_k.export
		output wire [4:0]  csr_l,                      //                     csr_l.export
		output wire [7:0]  csr_m,                      //                     csr_m.export
		output wire [4:0]  csr_n,                      //                     csr_n.export
		output wire [4:0]  csr_s,                      //                     csr_s.export
		output wire [4:0]  csr_cf,                     //                    csr_cf.export
		output wire [1:0]  csr_cs,                     //                    csr_cs.export
		output wire        csr_hd,                     //                    csr_hd.export
		output wire [4:0]  csr_np,                     //                    csr_np.export
		output wire [1:0]  csr_lane_powerdown,         //        csr_lane_powerdown.export
		output wire [1:0]  rxphy_clk,                  //                 rxphy_clk.export
		input  wire [1:0]  rx_serial_data,             //            rx_serial_data.rx_serial_data
		input  wire [1:0]  rx_analogreset,             //            rx_analogreset.rx_analogreset
		input  wire [1:0]  rx_digitalreset,            //           rx_digitalreset.rx_digitalreset
		output wire [1:0]  rx_islockedtodata,          //         rx_islockedtodata.rx_is_lockedtodata
		output wire [1:0]  rx_cal_busy                 //               rx_cal_busy.rx_cal_busy
	);

	wire  [63:0] inst_phy_jesd204_rx_pcs_data_export;       // inst_phy:jesd204_rx_pcs_data -> inst_rx:jesd204_rx_pcs_data
	wire   [1:0] inst_phy_jesd204_rx_pcs_data_valid_export; // inst_phy:jesd204_rx_pcs_data_valid -> inst_rx:jesd204_rx_pcs_data_valid
	wire   [7:0] inst_phy_jesd204_rx_pcs_kchar_data_export; // inst_phy:jesd204_rx_pcs_kchar_data -> inst_rx:jesd204_rx_pcs_kchar_data
	wire   [7:0] inst_phy_jesd204_rx_pcs_errdetect_export;  // inst_phy:jesd204_rx_pcs_errdetect -> inst_rx:jesd204_rx_pcs_errdetect
	wire   [7:0] inst_phy_jesd204_rx_pcs_disperr_export;    // inst_phy:jesd204_rx_pcs_disperr -> inst_rx:jesd204_rx_pcs_disperr
	wire   [1:0] inst_rx_csr_lane_polarity_export;          // inst_rx:csr_lane_polarity -> inst_phy:csr_lane_polarity
	wire         inst_rx_csr_bit_reversal_export;           // inst_rx:csr_bit_reversal -> inst_phy:csr_bit_reversal
	wire         inst_rx_csr_byte_reversal_export;          // inst_rx:csr_byte_reversal -> inst_phy:csr_byte_reversal
	wire   [1:0] inst_rx_patternalign_en_export;            // inst_rx:patternalign_en -> inst_phy:patternalign_en
	wire   [1:0] inst_phy_phy_csr_rx_pcfifo_full_export;    // inst_phy:phy_csr_rx_pcfifo_full -> inst_rx:phy_csr_rx_pcfifo_full
	wire   [1:0] inst_phy_phy_csr_rx_pcfifo_empty_export;   // inst_phy:phy_csr_rx_pcfifo_empty -> inst_rx:phy_csr_rx_pcfifo_empty

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (DEVICE_FAMILY != "Arria 10")
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					device_family_check ( .error(1'b1) );
		end
		if (SUBCLASSV != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					subclassv_check ( .error(1'b1) );
		end
		if (PCS_CONFIG != "JESD_PCS_CFG1")
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					pcs_config_check ( .error(1'b1) );
		end
		if (L != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					l_check ( .error(1'b1) );
		end
		if (M != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					m_check ( .error(1'b1) );
		end
		if (F != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f_check ( .error(1'b1) );
		end
		if (N != 14)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					n_check ( .error(1'b1) );
		end
		if (N_PRIME != 16)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					n_prime_check ( .error(1'b1) );
		end
		if (S != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s_check ( .error(1'b1) );
		end
		if (K != 16)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					k_check ( .error(1'b1) );
		end
		if (SCR != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					scr_check ( .error(1'b1) );
		end
		if (CS != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					cs_check ( .error(1'b1) );
		end
		if (CF != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					cf_check ( .error(1'b1) );
		end
		if (HD != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					hd_check ( .error(1'b1) );
		end
		if (ECC_EN != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ecc_en_check ( .error(1'b1) );
		end
		if (DLB_TEST != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					dlb_test_check ( .error(1'b1) );
		end
		if (PHADJ != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					phadj_check ( .error(1'b1) );
		end
		if (ADJCNT != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					adjcnt_check ( .error(1'b1) );
		end
		if (ADJDIR != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					adjdir_check ( .error(1'b1) );
		end
		if (OPTIMIZE != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					optimize_check ( .error(1'b1) );
		end
		if (DID != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					did_check ( .error(1'b1) );
		end
		if (BID != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					bid_check ( .error(1'b1) );
		end
		if (LID0 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid0_check ( .error(1'b1) );
		end
		if (FCHK0 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk0_check ( .error(1'b1) );
		end
		if (LID1 != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid1_check ( .error(1'b1) );
		end
		if (FCHK1 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk1_check ( .error(1'b1) );
		end
		if (LID2 != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid2_check ( .error(1'b1) );
		end
		if (FCHK2 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk2_check ( .error(1'b1) );
		end
		if (LID3 != 3)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid3_check ( .error(1'b1) );
		end
		if (FCHK3 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk3_check ( .error(1'b1) );
		end
		if (LID4 != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid4_check ( .error(1'b1) );
		end
		if (FCHK4 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk4_check ( .error(1'b1) );
		end
		if (LID5 != 5)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid5_check ( .error(1'b1) );
		end
		if (FCHK5 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk5_check ( .error(1'b1) );
		end
		if (LID6 != 6)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid6_check ( .error(1'b1) );
		end
		if (FCHK6 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk6_check ( .error(1'b1) );
		end
		if (LID7 != 7)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid7_check ( .error(1'b1) );
		end
		if (FCHK7 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk7_check ( .error(1'b1) );
		end
		if (JESDV != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					jesdv_check ( .error(1'b1) );
		end
		if (PMA_WIDTH != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					pma_width_check ( .error(1'b1) );
		end
		if (SER_SIZE != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ser_size_check ( .error(1'b1) );
		end
		if (FK != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fk_check ( .error(1'b1) );
		end
		if (RES1 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					res1_check ( .error(1'b1) );
		end
		if (RES2 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					res2_check ( .error(1'b1) );
		end
		if (BIT_REVERSAL != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					bit_reversal_check ( .error(1'b1) );
		end
		if (BYTE_REVERSAL != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					byte_reversal_check ( .error(1'b1) );
		end
		if (ALIGNMENT_PATTERN != 658812)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					alignment_pattern_check ( .error(1'b1) );
		end
		if (PULSE_WIDTH != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					pulse_width_check ( .error(1'b1) );
		end
		if (LS_FIFO_DEPTH != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ls_fifo_depth_check ( .error(1'b1) );
		end
		if (LS_FIFO_WIDTHU != 5)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ls_fifo_widthu_check ( .error(1'b1) );
		end
		if (UNUSED_TX_PARALLEL_WIDTH != 92)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					unused_tx_parallel_width_check ( .error(1'b1) );
		end
		if (UNUSED_RX_PARALLEL_WIDTH != 72)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					unused_rx_parallel_width_check ( .error(1'b1) );
		end
		if (XCVR_PLL_LOCKED_WIDTH != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					xcvr_pll_locked_width_check ( .error(1'b1) );
		end
		if (RECONFIG_ADDRESS_WIDTH != 11)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					reconfig_address_width_check ( .error(1'b1) );
		end
	endgenerate

	altera_jesd204_rx_base #(
		.DEVICE_FAMILY  ("Arria 10"),
		.SUBCLASSV      (1),
		.L              (2),
		.M              (2),
		.F              (2),
		.N              (14),
		.N_PRIME        (16),
		.S              (1),
		.K              (16),
		.SCR            (1),
		.CS             (0),
		.CF             (0),
		.HD             (0),
		.ECC_EN         (0),
		.DLB_TEST       (0),
		.JESDV          (1),
		.FK             (32),
		.BIT_REVERSAL   (0),
		.BYTE_REVERSAL  (0),
		.PULSE_WIDTH    (2),
		.LS_FIFO_DEPTH  (32),
		.LS_FIFO_WIDTHU (5)
	) inst_rx (
		.rxlink_clk                 (rxlink_clk),                                //                rxlink_clk.clk
		.rxlink_rst_n               (rxlink_rst_n_reset_n),                      //              rxlink_rst_n.reset_n
		.jesd204_rx_avs_clk         (jesd204_rx_avs_clk),                        //        jesd204_rx_avs_clk.clk
		.jesd204_rx_avs_rst_n       (jesd204_rx_avs_rst_n),                      //      jesd204_rx_avs_rst_n.reset_n
		.jesd204_rx_avs_chipselect  (jesd204_rx_avs_chipselect),                 //            jesd204_rx_avs.chipselect
		.jesd204_rx_avs_address     (jesd204_rx_avs_address),                    //                          .address
		.jesd204_rx_avs_read        (jesd204_rx_avs_read),                       //                          .read
		.jesd204_rx_avs_readdata    (jesd204_rx_avs_readdata),                   //                          .readdata
		.jesd204_rx_avs_waitrequest (jesd204_rx_avs_waitrequest),                //                          .waitrequest
		.jesd204_rx_avs_write       (jesd204_rx_avs_write),                      //                          .write
		.jesd204_rx_avs_writedata   (jesd204_rx_avs_writedata),                  //                          .writedata
		.jesd204_rx_link_data       (jesd204_rx_link_data),                      //                   avst_rx.data
		.jesd204_rx_link_valid      (jesd204_rx_link_valid),                     //                          .valid
		.jesd204_rx_link_ready      (jesd204_rx_link_ready),                     //                          .ready
		.sof                        (sof),                                       //                       sof.export
		.somf                       (somf),                                      //                      somf.export
		.alldev_lane_aligned        (alldev_lane_aligned),                       //       alldev_lane_aligned.export
		.dev_lane_aligned           (dev_lane_aligned),                          //          dev_lane_aligned.export
		.dev_sync_n                 (dev_sync_n),                                //                dev_sync_n.export
		.sysref                     (sysref),                                    //                    sysref.export
		.jesd204_rx_int             (jesd204_rx_int),                            //            jesd204_rx_int.irq
		.csr_rx_testmode            (csr_rx_testmode),                           //           csr_rx_testmode.export
		.csr_f                      (csr_f),                                     //                     csr_f.export
		.csr_k                      (csr_k),                                     //                     csr_k.export
		.csr_l                      (csr_l),                                     //                     csr_l.export
		.csr_m                      (csr_m),                                     //                     csr_m.export
		.csr_n                      (csr_n),                                     //                     csr_n.export
		.csr_s                      (csr_s),                                     //                     csr_s.export
		.csr_cf                     (csr_cf),                                    //                    csr_cf.export
		.csr_cs                     (csr_cs),                                    //                    csr_cs.export
		.csr_hd                     (csr_hd),                                    //                    csr_hd.export
		.csr_np                     (csr_np),                                    //                    csr_np.export
		.csr_byte_reversal          (inst_rx_csr_byte_reversal_export),          //         csr_byte_reversal.export
		.csr_bit_reversal           (inst_rx_csr_bit_reversal_export),           //          csr_bit_reversal.export
		.csr_lane_polarity          (inst_rx_csr_lane_polarity_export),          //         csr_lane_polarity.export
		.csr_lane_powerdown         (csr_lane_powerdown),                        //        csr_lane_powerdown.export
		.jesd204_rx_frame_error     (jesd204_rx_frame_error),                    //    jesd204_rx_frame_error.export
		.jesd204_rx_pcs_data        (inst_phy_jesd204_rx_pcs_data_export),       //       jesd204_rx_pcs_data.export
		.jesd204_rx_pcs_data_valid  (inst_phy_jesd204_rx_pcs_data_valid_export), // jesd204_rx_pcs_data_valid.export
		.jesd204_rx_pcs_kchar_data  (inst_phy_jesd204_rx_pcs_kchar_data_export), // jesd204_rx_pcs_kchar_data.export
		.jesd204_rx_pcs_errdetect   (inst_phy_jesd204_rx_pcs_errdetect_export),  //  jesd204_rx_pcs_errdetect.export
		.jesd204_rx_pcs_disperr     (inst_phy_jesd204_rx_pcs_disperr_export),    //    jesd204_rx_pcs_disperr.export
		.patternalign_en            (inst_rx_patternalign_en_export),            //           patternalign_en.export
		.phy_csr_rx_pcfifo_empty    (inst_phy_phy_csr_rx_pcfifo_empty_export),   //   phy_csr_rx_pcfifo_empty.export
		.phy_csr_rx_pcfifo_full     (inst_phy_phy_csr_rx_pcfifo_full_export),    //    phy_csr_rx_pcfifo_full.export
		.phy_csr_rx_cal_busy        (rx_cal_busy),                               //       phy_csr_rx_cal_busy.rx_cal_busy
		.phy_csr_rx_locked_to_data  (rx_islockedtodata),                         // phy_csr_rx_locked_to_data.rx_is_lockedtodata
		.jesd204_rx_dlb_data        (jesd204_rx_dlb_data),                       //       jesd204_rx_dlb_data.export
		.jesd204_rx_dlb_data_valid  (jesd204_rx_dlb_data_valid),                 // jesd204_rx_dlb_data_valid.export
		.jesd204_rx_dlb_kchar_data  (jesd204_rx_dlb_kchar_data),                 // jesd204_rx_dlb_kchar_data.export
		.jesd204_rx_dlb_errdetect   (jesd204_rx_dlb_errdetect),                  //  jesd204_rx_dlb_errdetect.export
		.jesd204_rx_dlb_disperr     (jesd204_rx_dlb_disperr)                     //    jesd204_rx_dlb_disperr.export
	);

	jesd204b_altera_jesd204_phy_161_yorkvea #(
		.DEVICE_FAMILY            ("Arria 10"),
		.L                        (2),
		.PCS_CONFIG               ("JESD_PCS_CFG1"),
		.PMA_WIDTH                (32),
		.SER_SIZE                 (4),
		.ALIGNMENT_PATTERN        (658812),
		.UNUSED_TX_PARALLEL_WIDTH (92),
		.UNUSED_RX_PARALLEL_WIDTH (72),
		.XCVR_PLL_LOCKED_WIDTH    (2),
		.RECONFIG_ADDRESS_WIDTH   (11)
	) inst_phy (
		.pll_ref_clk               (pll_ref_clk),                               //               pll_ref_clk.clk
		.rxlink_clk                (rxlink_clk),                                //                rxlink_clk.clk
		.rxlink_rst_n              (rxlink_rst_n_reset_n),                      //              rxlink_rst_n.reset_n
		.csr_lane_polarity         (inst_rx_csr_lane_polarity_export),          //         csr_lane_polarity.export
		.csr_bit_reversal          (inst_rx_csr_bit_reversal_export),           //          csr_bit_reversal.export
		.csr_byte_reversal         (inst_rx_csr_byte_reversal_export),          //         csr_byte_reversal.export
		.csr_lane_powerdown        (csr_lane_powerdown),                        //        csr_lane_powerdown.export
		.patternalign_en           (inst_rx_patternalign_en_export),            //           patternalign_en.export
		.jesd204_rx_pcs_data       (inst_phy_jesd204_rx_pcs_data_export),       //       jesd204_rx_pcs_data.export
		.jesd204_rx_pcs_data_valid (inst_phy_jesd204_rx_pcs_data_valid_export), // jesd204_rx_pcs_data_valid.export
		.jesd204_rx_pcs_kchar_data (inst_phy_jesd204_rx_pcs_kchar_data_export), // jesd204_rx_pcs_kchar_data.export
		.jesd204_rx_pcs_errdetect  (inst_phy_jesd204_rx_pcs_errdetect_export),  //  jesd204_rx_pcs_errdetect.export
		.jesd204_rx_pcs_disperr    (inst_phy_jesd204_rx_pcs_disperr_export),    //    jesd204_rx_pcs_disperr.export
		.phy_csr_rx_locked_to_data (rx_islockedtodata),                         // phy_csr_rx_locked_to_data.rx_is_lockedtodata
		.phy_csr_rx_cal_busy       (rx_cal_busy),                               //       phy_csr_rx_cal_busy.rx_cal_busy
		.phy_csr_rx_pcfifo_full    (inst_phy_phy_csr_rx_pcfifo_full_export),    //    phy_csr_rx_pcfifo_full.export
		.phy_csr_rx_pcfifo_empty   (inst_phy_phy_csr_rx_pcfifo_empty_export),   //   phy_csr_rx_pcfifo_empty.export
		.rx_serial_data            (rx_serial_data),                            //            rx_serial_data.rx_serial_data
		.rx_analogreset            (rx_analogreset),                            //            rx_analogreset.rx_analogreset
		.rx_digitalreset           (rx_digitalreset),                           //           rx_digitalreset.rx_digitalreset
		.rxphy_clk                 (rxphy_clk)                                  //                 rxphy_clk.export
	);

endmodule
