config alt_sld_fab_alt_sld_fab_161_3dkcx2q_cfg;
		design alt_sld_fab_alt_sld_fab_161_3dkcx2q;
		instance alt_sld_fab_alt_sld_fab_161_3dkcx2q.presplit use alt_sld_fab_altera_super_splitter_161.alt_sld_fab_altera_super_splitter_161_ksmztdy;
		instance alt_sld_fab_alt_sld_fab_161_3dkcx2q.splitter use alt_sld_fab_altera_sld_splitter_161.alt_sld_fab_altera_sld_splitter_161_kh7iddq;
		instance alt_sld_fab_alt_sld_fab_161_3dkcx2q.a10xcvrfabric use alt_sld_fab_altera_a10_xcvr_reset_sequencer_161.alt_sld_fab_altera_a10_xcvr_reset_sequencer_161_a5febdq;
endconfig

