config alt_sld_fab_alt_sld_fab_161_c3nzqia_cfg;
		design alt_sld_fab_alt_sld_fab_161_c3nzqia;
		instance alt_sld_fab_alt_sld_fab_161_c3nzqia.presplit use alt_sld_fab_altera_super_splitter_161.alt_sld_fab_altera_super_splitter_161_ksmztdy;
		instance alt_sld_fab_alt_sld_fab_161_c3nzqia.splitter use alt_sld_fab_altera_sld_splitter_161.alt_sld_fab_altera_sld_splitter_161_kh7iddq;
		instance alt_sld_fab_alt_sld_fab_161_c3nzqia.a10xcvrfabric use alt_sld_fab_altera_a10_xcvr_reset_sequencer_161.alt_sld_fab_altera_a10_xcvr_reset_sequencer_161_a5febdq;
endconfig

