// fifo_56_28.v

// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module fifo_56_28 (
		input  wire [55:0] data,    //  fifo_input.datain
		input  wire        wrreq,   //            .wrreq
		input  wire        rdreq,   //            .rdreq
		input  wire        wrclk,   //            .wrclk
		input  wire        rdclk,   //            .rdclk
		output wire [27:0] q,       // fifo_output.dataout
		output wire        rdempty  //            .rdempty
	);

	fifo_56_28_fifo_161_jjnbjqy fifo_0 (
		.data    (data),    //  fifo_input.datain
		.wrreq   (wrreq),   //            .wrreq
		.rdreq   (rdreq),   //            .rdreq
		.wrclk   (wrclk),   //            .wrclk
		.rdclk   (rdclk),   //            .rdclk
		.q       (q),       // fifo_output.dataout
		.rdempty (rdempty)  //            .rdempty
	);

endmodule
