

vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/altera_xcvr_functions.sv"                  -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/alt_xcvr_resync.sv"                        -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/altera_xcvr_reset_control.sv"              -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/altera_xcvr_reset_control_161/sim/alt_xcvr_reset_counter.sv"                 -work tb_tx_phyrst_ctl_altera_xcvr_reset_control_161 
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tb_tx_phyrst_ctl/sim/tb_tx_phyrst_ctl.v"                                                                                                           
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/fifo_56_28/fifo_56_28/fifo_161/sim/fifo_56_28_fifo_161_jjnbjqy.v"                             -work fifo_56_28_fifo_161                            
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/fifo_56_28/fifo_56_28/sim/fifo_56_28.v"                                                                                                            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_a10_functions_h.sv"             -work altera_common_sv_packages                      
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_resync.sv"                                -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_arbiter.sv"                               -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pcs.sv"                                   -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pma.sv"                                   -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_avmm.sv"                             -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_native.sv"                           -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/a10_avmm_h.sv"                                     -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_pipe_retry.sv"                     -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_avmm_csr.sv"                       -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_prbs_accum.sv"                     -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_odi_accel.sv"                      -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_arb.sv"                       -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_params_h.sv"           -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_commands_h.sv"                           -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_functions_h.sv"                          -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_program.sv"                              -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_cpu.sv"                                  -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_master.sv"                               -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_ip.sv"                 -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/tx_jesd204b_altera_xcvr_native_a10_161_6d2kjaq.sv" -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_opt_logic_6d2kjaq.sv"         -work tx_jesd204b_altera_xcvr_native_a10_161         
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_phy_161/sim/tx_jesd204b_altera_jesd204_phy_161_bhvxniy.v"          -work tx_jesd204b_altera_jesd204_phy_161             
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/altera_jesd204_161/sim/tx_jesd204b_altera_jesd204_161_py6ow4q.v"                  -work tx_jesd204b_altera_jesd204_161                 
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/tx_jesd204b/sim/tx_jesd204b.v"                                                                                                                     
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/rom_port/rom_1port_161/sim/rom_port_rom_1port_161_m5cej6i.v"                                  -work rom_port_rom_1port_161                         
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/rom_port/sim/rom_port.v"                                                                                                                           
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/altera_xcvr_functions.sv"                 -work phyrst_controller_altera_xcvr_reset_control_161
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/alt_xcvr_resync.sv"                       -work phyrst_controller_altera_xcvr_reset_control_161
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/altera_xcvr_reset_control.sv"             -work phyrst_controller_altera_xcvr_reset_control_161
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/altera_xcvr_reset_control_161/sim/alt_xcvr_reset_counter.sv"                -work phyrst_controller_altera_xcvr_reset_control_161
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/phyrst_controller/sim/phyrst_controller.v"                                                                                                         
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_resync.sv"                                   -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_arbiter.sv"                                  -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pcs.sv"                                      -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_pma.sv"                                      -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_avmm.sv"                                -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/twentynm_xcvr_native.sv"                              -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/a10_avmm_h.sv"                                        -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_pipe_retry.sv"                        -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_avmm_csr.sv"                          -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_prbs_accum.sv"                        -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_odi_accel.sv"                         -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_arb.sv"                          -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_params_h.sv"              -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_commands_h.sv"                              -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_functions_h.sv"                             -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_program.sv"                                 -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_cpu.sv"                                     -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/pcie_mgmt_master.sv"                                  -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/altera_xcvr_native_pcie_dfe_ip.sv"                    -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/jesd204b_altera_xcvr_native_a10_161_ou2lroi.sv"       -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_xcvr_native_a10_161/sim/alt_xcvr_native_rcfg_opt_logic_ou2lroi.sv"            -work jesd204b_altera_xcvr_native_a10_161            
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_phy_161/sim/jesd204b_altera_jesd204_phy_161_yorkvea.v"                -work jesd204b_altera_jesd204_phy_161                
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/altera_jesd204_161/sim/jesd204b_altera_jesd204_161_zta4dmq.v"                        -work jesd204b_altera_jesd204_161                    
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/jesd204b/sim/jesd204b.v"                                                                                                                           
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/core_pll/altera_iopll_161/sim/core_pll_altera_iopll_161_ep46qai.vo"                           -work core_pll_altera_iopll_161                      
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/core_pll/sim/core_pll.v"                                                                                                                           
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/twentynm_xcvr_avmm.sv"                                -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_resync.sv"                                   -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_arbiter.sv"                                  -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/a10_avmm_h.sv"                                        -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_atx_pll_rcfg_arb.sv"                         -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/a10_xcvr_atx_pll.sv"                                  -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_pll_embedded_debug.sv"                       -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_pll_avmm_csr.sv"                             -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/atx_pll_altera_xcvr_atx_pll_a10_161_25ew5mi.sv"       -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k -sverilog "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/altera_xcvr_atx_pll_a10_161/sim/alt_xcvr_atx_pll_rcfg_opt_logic_25ew5mi.sv"           -work atx_pll_altera_xcvr_atx_pll_a10_161            
vlogan +v2k           "F:/Project_Fiels/TXY/MS/cpy/program/FPGA/AD9250_test/ip_core/atx_pll/sim/atx_pll.v"                                                                                                                             
