	jesd204b u0 (
		.pll_ref_clk                (<connected-to-pll_ref_clk>),                //               pll_ref_clk.clk
		.rxlink_clk                 (<connected-to-rxlink_clk>),                 //                rxlink_clk.clk
		.rxlink_rst_n_reset_n       (<connected-to-rxlink_rst_n_reset_n>),       //              rxlink_rst_n.reset_n
		.jesd204_rx_avs_clk         (<connected-to-jesd204_rx_avs_clk>),         //        jesd204_rx_avs_clk.clk
		.jesd204_rx_avs_rst_n       (<connected-to-jesd204_rx_avs_rst_n>),       //      jesd204_rx_avs_rst_n.reset_n
		.jesd204_rx_avs_chipselect  (<connected-to-jesd204_rx_avs_chipselect>),  //            jesd204_rx_avs.chipselect
		.jesd204_rx_avs_address     (<connected-to-jesd204_rx_avs_address>),     //                          .address
		.jesd204_rx_avs_read        (<connected-to-jesd204_rx_avs_read>),        //                          .read
		.jesd204_rx_avs_readdata    (<connected-to-jesd204_rx_avs_readdata>),    //                          .readdata
		.jesd204_rx_avs_waitrequest (<connected-to-jesd204_rx_avs_waitrequest>), //                          .waitrequest
		.jesd204_rx_avs_write       (<connected-to-jesd204_rx_avs_write>),       //                          .write
		.jesd204_rx_avs_writedata   (<connected-to-jesd204_rx_avs_writedata>),   //                          .writedata
		.jesd204_rx_link_data       (<connected-to-jesd204_rx_link_data>),       //           jesd204_rx_link.data
		.jesd204_rx_link_valid      (<connected-to-jesd204_rx_link_valid>),      //                          .valid
		.jesd204_rx_link_ready      (<connected-to-jesd204_rx_link_ready>),      //                          .ready
		.jesd204_rx_dlb_data        (<connected-to-jesd204_rx_dlb_data>),        //       jesd204_rx_dlb_data.export
		.jesd204_rx_dlb_data_valid  (<connected-to-jesd204_rx_dlb_data_valid>),  // jesd204_rx_dlb_data_valid.export
		.jesd204_rx_dlb_kchar_data  (<connected-to-jesd204_rx_dlb_kchar_data>),  // jesd204_rx_dlb_kchar_data.export
		.jesd204_rx_dlb_errdetect   (<connected-to-jesd204_rx_dlb_errdetect>),   //  jesd204_rx_dlb_errdetect.export
		.jesd204_rx_dlb_disperr     (<connected-to-jesd204_rx_dlb_disperr>),     //    jesd204_rx_dlb_disperr.export
		.alldev_lane_aligned        (<connected-to-alldev_lane_aligned>),        //       alldev_lane_aligned.export
		.sysref                     (<connected-to-sysref>),                     //                    sysref.export
		.jesd204_rx_frame_error     (<connected-to-jesd204_rx_frame_error>),     //    jesd204_rx_frame_error.export
		.jesd204_rx_int             (<connected-to-jesd204_rx_int>),             //            jesd204_rx_int.irq
		.csr_rx_testmode            (<connected-to-csr_rx_testmode>),            //           csr_rx_testmode.export
		.dev_lane_aligned           (<connected-to-dev_lane_aligned>),           //          dev_lane_aligned.export
		.dev_sync_n                 (<connected-to-dev_sync_n>),                 //                dev_sync_n.export
		.sof                        (<connected-to-sof>),                        //                       sof.export
		.somf                       (<connected-to-somf>),                       //                      somf.export
		.csr_f                      (<connected-to-csr_f>),                      //                     csr_f.export
		.csr_k                      (<connected-to-csr_k>),                      //                     csr_k.export
		.csr_l                      (<connected-to-csr_l>),                      //                     csr_l.export
		.csr_m                      (<connected-to-csr_m>),                      //                     csr_m.export
		.csr_n                      (<connected-to-csr_n>),                      //                     csr_n.export
		.csr_s                      (<connected-to-csr_s>),                      //                     csr_s.export
		.csr_cf                     (<connected-to-csr_cf>),                     //                    csr_cf.export
		.csr_cs                     (<connected-to-csr_cs>),                     //                    csr_cs.export
		.csr_hd                     (<connected-to-csr_hd>),                     //                    csr_hd.export
		.csr_np                     (<connected-to-csr_np>),                     //                    csr_np.export
		.csr_lane_powerdown         (<connected-to-csr_lane_powerdown>),         //        csr_lane_powerdown.export
		.rxphy_clk                  (<connected-to-rxphy_clk>),                  //                 rxphy_clk.export
		.rx_serial_data             (<connected-to-rx_serial_data>),             //            rx_serial_data.rx_serial_data
		.rx_analogreset             (<connected-to-rx_analogreset>),             //            rx_analogreset.rx_analogreset
		.rx_digitalreset            (<connected-to-rx_digitalreset>),            //           rx_digitalreset.rx_digitalreset
		.rx_islockedtodata          (<connected-to-rx_islockedtodata>),          //         rx_islockedtodata.rx_is_lockedtodata
		.rx_cal_busy                (<connected-to-rx_cal_busy>)                 //               rx_cal_busy.rx_cal_busy
	);

