	tx_jesd204b u0 (
		.csr_cf                     (<connected-to-csr_cf>),                     //                    csr_cf.export
		.csr_cs                     (<connected-to-csr_cs>),                     //                    csr_cs.export
		.csr_f                      (<connected-to-csr_f>),                      //                     csr_f.export
		.csr_hd                     (<connected-to-csr_hd>),                     //                    csr_hd.export
		.csr_k                      (<connected-to-csr_k>),                      //                     csr_k.export
		.csr_l                      (<connected-to-csr_l>),                      //                     csr_l.export
		.csr_lane_powerdown         (<connected-to-csr_lane_powerdown>),         //        csr_lane_powerdown.export
		.csr_m                      (<connected-to-csr_m>),                      //                     csr_m.export
		.csr_n                      (<connected-to-csr_n>),                      //                     csr_n.export
		.csr_np                     (<connected-to-csr_np>),                     //                    csr_np.export
		.csr_s                      (<connected-to-csr_s>),                      //                     csr_s.export
		.csr_tx_testmode            (<connected-to-csr_tx_testmode>),            //           csr_tx_testmode.export
		.csr_tx_testpattern_a       (<connected-to-csr_tx_testpattern_a>),       //      csr_tx_testpattern_a.export
		.csr_tx_testpattern_b       (<connected-to-csr_tx_testpattern_b>),       //      csr_tx_testpattern_b.export
		.csr_tx_testpattern_c       (<connected-to-csr_tx_testpattern_c>),       //      csr_tx_testpattern_c.export
		.csr_tx_testpattern_d       (<connected-to-csr_tx_testpattern_d>),       //      csr_tx_testpattern_d.export
		.dev_sync_n                 (<connected-to-dev_sync_n>),                 //                dev_sync_n.export
		.jesd204_tx_avs_chipselect  (<connected-to-jesd204_tx_avs_chipselect>),  //            jesd204_tx_avs.chipselect
		.jesd204_tx_avs_address     (<connected-to-jesd204_tx_avs_address>),     //                          .address
		.jesd204_tx_avs_read        (<connected-to-jesd204_tx_avs_read>),        //                          .read
		.jesd204_tx_avs_readdata    (<connected-to-jesd204_tx_avs_readdata>),    //                          .readdata
		.jesd204_tx_avs_waitrequest (<connected-to-jesd204_tx_avs_waitrequest>), //                          .waitrequest
		.jesd204_tx_avs_write       (<connected-to-jesd204_tx_avs_write>),       //                          .write
		.jesd204_tx_avs_writedata   (<connected-to-jesd204_tx_avs_writedata>),   //                          .writedata
		.jesd204_tx_avs_clk         (<connected-to-jesd204_tx_avs_clk>),         //        jesd204_tx_avs_clk.clk
		.jesd204_tx_avs_rst_n       (<connected-to-jesd204_tx_avs_rst_n>),       //      jesd204_tx_avs_rst_n.reset_n
		.jesd204_tx_dlb_data        (<connected-to-jesd204_tx_dlb_data>),        //       jesd204_tx_dlb_data.export
		.jesd204_tx_dlb_kchar_data  (<connected-to-jesd204_tx_dlb_kchar_data>),  // jesd204_tx_dlb_kchar_data.export
		.jesd204_tx_frame_error     (<connected-to-jesd204_tx_frame_error>),     //    jesd204_tx_frame_error.export
		.jesd204_tx_frame_ready     (<connected-to-jesd204_tx_frame_ready>),     //    jesd204_tx_frame_ready.export
		.jesd204_tx_int             (<connected-to-jesd204_tx_int>),             //            jesd204_tx_int.irq
		.jesd204_tx_link_data       (<connected-to-jesd204_tx_link_data>),       //           jesd204_tx_link.data
		.jesd204_tx_link_valid      (<connected-to-jesd204_tx_link_valid>),      //                          .valid
		.jesd204_tx_link_ready      (<connected-to-jesd204_tx_link_ready>),      //                          .ready
		.mdev_sync_n                (<connected-to-mdev_sync_n>),                //               mdev_sync_n.export
		.pll_locked                 (<connected-to-pll_locked>),                 //                pll_locked.pll_locked
		.sync_n                     (<connected-to-sync_n>),                     //                    sync_n.export
		.sysref                     (<connected-to-sysref>),                     //                    sysref.export
		.tx_analogreset             (<connected-to-tx_analogreset>),             //            tx_analogreset.tx_analogreset
		.tx_bonding_clocks_ch0      (<connected-to-tx_bonding_clocks_ch0>),      //     tx_bonding_clocks_ch0.clk
		.tx_bonding_clocks_ch1      (<connected-to-tx_bonding_clocks_ch1>),      //     tx_bonding_clocks_ch1.clk
		.tx_cal_busy                (<connected-to-tx_cal_busy>),                //               tx_cal_busy.tx_cal_busy
		.tx_digitalreset            (<connected-to-tx_digitalreset>),            //           tx_digitalreset.tx_digitalreset
		.tx_serial_data             (<connected-to-tx_serial_data>),             //            tx_serial_data.tx_serial_data
		.txlink_clk                 (<connected-to-txlink_clk>),                 //                txlink_clk.clk
		.txlink_rst_n_reset_n       (<connected-to-txlink_rst_n_reset_n>),       //              txlink_rst_n.reset_n
		.txphy_clk                  (<connected-to-txphy_clk>)                   //                 txphy_clk.export
	);

